### ISSUE TITLE
Need a better name for the package

### ISSUE THREAD

**Issue by pmendes** [tesladdicts/teslajson#3]
I think we should get a unique name for this package. There is the original already called teslajson and many forks. Since we now also do SQL the name is not reflecting much of this anymore.

Ideally name should highlight one or several of the following characteristics: a) this gets detailed statistics (not yet too sophisticated but I have big plans), b) the data stays with the user, c) it's open source, d) it's python

Alternatively just a name that sticks and is not an acronym (probably better).

**Comment by LelandSindt** [comment]
https://en.wiktionary.org/wiki/testatus

**Comment by pmendes** [comment]
_testatus_  I like it!

**Comment by SethRobertson** [comment]
I don't have a better idea, so I guess it is a go.  I wonder if github puts redirection links on repo renames.  I guess I'll find out.
