### ISSUE TITLE
Logger keeps car from sleeping since firmware 2019.8.5

### ISSUE THREAD

**Issue by pmendes** [tesladdicts/teslajson#5]
Since firmware 2019.8.5 (or maybe even 2019.8.3), the logger now prevents the car from sleeping resulting in about 20 miles/day charge lost when it is parked. It seems this has been confirmed by other apps and some changes are required. 

I will try to address this soon, but cannot promise when. First issue is understanding what has changed so that a solution can be adopted.

**Comment by pmendes** [comment]
I found a resolution to this which is to increase the "to_sleep" timing to 900 (15 minutes). This can easily be done in the command line with `--intervals "to_sleep=900"`. However I think that we should probably change the default as with the new firmware the default value will just keep the car awake at all times, leading to huge drains on the battery...

"to_sleep" is the time that the poller is inactive if it detects that the car is attempting to enter sleep mode. The 900 value corresponds to 15 minutes which I found is enough to allow it to enter sleep mode.

**Comment by SethRobertson** [comment]
Default changed.

Did you experiment to see if this was the minimum value?

**Comment by pmendes** [comment]
I did not nail it down to the 15 minutes, but trying 10 minutes did not work, so I think 15 minutes is ok (it's what  people use with teslafi...)

Having said this, I think there are more issues that prevent the car entering sleep than just this wait time. Today my car did 4 rounds of "to_sleep" status before entering sleep, yesterday it never entered sleep, but at work it had no problem. Some people have suggested that this has to do with the wifi connection (when it senses wifi it does not sleep). I'm keeping an eye on this issue
