### ISSUE TITLE
error in tesla_parser.py since change in API version 10

### ISSUE THREAD

**Issue by pmendes** [tesladdicts/teslajson#8]
Starting from August 27 2020, the tesla API version 10 is including 
` "vehicle_config": null `
when the car state is "asleep". This then results in an error in the tesla_parselib.py :
```
  File "build/bdist.linux-x86_64/egg/tesla_parselib.py", line 48, in __init__
  File "build/bdist.linux-x86_64/egg/tesla_parselib.py", line 121, in _jget
TypeError: argument of type 'NoneType' is not iterable
```
lines 48-54 would get the details of the vehicle_config, but _jget cannot deal with a null object.

A simple resolution would be to include lines 48-54 of tesla_parselib.py inside an 
`if self.state != "asleep":`
which I will be trying out

**Comment by pmendes** [comment]
Unfortunately the fix above does not work. It turns out that when the vehicle goes online it still issues a record with `"state": "online"` 
but which still has
`"vehicle_config" = null`
So checking the state is not enough. I think this probably needs to be fixed in _jget instead.

**Comment by pmendes** [comment]
I confirm the problem is the presence of
`"vehicle_config": null`
the files can be fixed by filtering with sed
`sed 's/\"vehicle_config\": null,//' original-file > new-file`
then running
`tesla-parser.py new-file`
runs without problems. This can be used as a temporary fix until we fix the bug

**Comment by SethRobertson** [comment]
Just pushed a fix that works for me.  No need to sed any files.
